"""Версионируемый каталог задач без уроков, теории и встроенного редактора.

Каждая задача указывает на реально доступную мишень приложения. Решение ученик
пишет в локальной IDE и помещает в ``student_tests``.
"""
from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class Text:
    ru: str
    en: str

    def in_language(self, language: str) -> str:
        return self.en if language == "en" else self.ru


@dataclass(frozen=True)
class Challenge:
    slug: str
    track: str
    difficulty: str
    title: Text
    task: Text
    target: str
    test_path: str
    criteria: tuple[Text, ...]
    markers: tuple[str, ...]


@dataclass(frozen=True)
class Track:
    slug: str
    title: Text
    description: Text
    challenges: tuple[Challenge, ...]


def _c(
    slug: str,
    track: str,
    difficulty: str,
    title_ru: str,
    title_en: str,
    task_ru: str,
    task_en: str,
    target: str,
    test_path: str,
    criteria: tuple[tuple[str, str], ...],
    markers: tuple[str, ...],
) -> Challenge:
    return Challenge(
        slug=slug,
        track=track,
        difficulty=difficulty,
        title=Text(title_ru, title_en),
        task=Text(task_ru, task_en),
        target=target,
        test_path=test_path,
        criteria=tuple(Text(ru, en) for ru, en in criteria),
        markers=markers,
    )


TRACKS: tuple[Track, ...] = (
    Track(
        "api-contracts",
        Text("API и контракты", "API and contracts"),
        Text(
            "HTTP-статусы, схемы, заголовки, пагинация и идемпотентность.",
            "HTTP statuses, schemas, headers, pagination, and idempotency.",
        ),
        (
            _c(
                "echo-contract", "api-contracts", "basic",
                "Контракт echo-запроса", "Echo request contract",
                "Проверьте передачу query-параметров, JSON-тела и пользовательского заголовка.",
                "Verify query parameters, JSON body, and a custom header.",
                "GET|POST /api/practice/echo", "student_tests/api/test_echo_contract.py",
                (("Позитивные GET и POST сценарии.", "Positive GET and POST scenarios."),
                 ("Проверка Content-Type и структуры JSON.", "Validate Content-Type and JSON structure."),
                 ("Параметризованные Unicode и пустые значения.", "Parametrized Unicode and empty values.")),
                ("api", "contract"),
            ),
            _c(
                "status-matrix", "api-contracts", "basic",
                "Матрица HTTP-статусов", "HTTP status matrix",
                "Параметризуйте проверку успешных и ошибочных HTTP-статусов.",
                "Parametrize successful and error HTTP statuses.",
                "GET /api/practice/status/{code}", "student_tests/api/test_status_matrix.py",
                (("Проверены 200, 201, 202, 204.", "Cover 200, 201, 202, and 204."),
                 ("Проверены 400, 404, 409, 429, 500, 503.", "Cover 400, 404, 409, 429, 500, and 503."),
                 ("Для 204 тело действительно пустое.", "The 204 response body is empty.")),
                ("api",),
            ),
            _c(
                "schema-variants", "api-contracts", "intermediate",
                "Негативные варианты схемы", "Negative schema variants",
                "Создайте контрактные проверки stable, nullable, missing, extra и wrong-type.",
                "Create contract checks for stable, nullable, missing, extra, and wrong-type variants.",
                "GET /api/practice/schema/{variant}", "student_tests/contract/test_schema_variants.py",
                (("Стабильная схема проходит строгую проверку.", "The stable schema passes strict validation."),
                 ("Каждая намеренная поломка обнаруживается отдельным тестом.", "Each deliberate break is detected by a separate test."),
                 ("Ошибка теста объясняет нарушенное поле.", "Failure output identifies the broken field.")),
                ("api", "contract"),
            ),
            _c(
                "resource-crud", "api-contracts", "intermediate",
                "Полный CRUD ресурса", "Complete resource CRUD",
                "Проверьте создание, чтение, изменение, удаление и повторное чтение.",
                "Verify create, read, update, delete, and read-after-delete.",
                "/api/practice/resources", "student_tests/api/test_resource_crud.py",
                (("Состояние изолировано уникальным X-Test-Run-Id.", "State is isolated by a unique X-Test-Run-Id."),
                 ("Проверяются коды, тело и серверные поля.", "Validate statuses, body, and server fields."),
                 ("После DELETE возвращается 404.", "GET after DELETE returns 404.")),
                ("api",),
            ),
            _c(
                "pagination-sort-search", "api-contracts", "intermediate",
                "Пагинация, сортировка и поиск", "Pagination, sorting, and search",
                "Создайте набор ресурсов и проверьте границы страниц, сортировку и фильтр.",
                "Create resources and verify page boundaries, sorting, and filtering.",
                "GET /api/practice/resources", "student_tests/api/test_resource_list.py",
                (("Проверены page, size, total и items.", "Validate page, size, total, and items."),
                 ("Проверены обе сортировки и регистронезависимый поиск.", "Validate both sort orders and case-insensitive search."),
                 ("Пустая страница не считается ошибкой.", "An empty page is not treated as an error.")),
                ("api",),
            ),
            _c(
                "idempotency-etag", "api-contracts", "advanced",
                "Идемпотентность и optimistic locking", "Idempotency and optimistic locking",
                "Проверьте Idempotency-Key, ETag, If-Match и конфликт версий.",
                "Verify Idempotency-Key, ETag, If-Match, and version conflicts.",
                "/api/practice/resources", "student_tests/api/test_resource_concurrency.py",
                (("Повторный POST с тем же ключом не создаёт дубль, а другое тело даёт 409.", "A repeated POST creates no duplicate; a different payload returns 409."),
                 ("PUT без If-Match даёт 428, устаревший — 412.", "PUT without If-Match returns 428; stale value returns 412."),
                 ("Успешное обновление меняет ETag.", "A successful update changes the ETag.")),
                ("api", "integration"),
            ),
        ),
    ),
    Track(
        "security",
        Text("Аутентификация и безопасность", "Authentication and security"),
        Text("JWT, роли, сессии, cookies, валидация и ограничения доступа.", "JWT, roles, sessions, cookies, validation, and access control."),
        (
            _c(
                "auth-lifecycle", "security", "intermediate",
                "Жизненный цикл токена", "Token lifecycle",
                "Проверьте login, refresh, доступ с access-токеном и отказы для неверных токенов.",
                "Verify login, refresh, access-token use, and invalid-token failures.",
                "/api/auth/* and /api/profile", "student_tests/api/test_auth_lifecycle.py",
                (("Секреты не выводятся в отчёт.", "Secrets are not written to the report."),
                 ("Проверены 401 и WWW-Authenticate.", "Validate 401 and WWW-Authenticate."),
                 ("Refresh-токен не принимается как access-токен.", "A refresh token is rejected as an access token.")),
                ("api", "security"),
            ),
            _c(
                "rbac-matrix", "security", "intermediate",
                "Матрица ролей RBAC", "RBAC role matrix",
                "Сравните разрешения USER и ADMIN на административных API.",
                "Compare USER and ADMIN permissions on administrative APIs.",
                "/api/admin/*", "student_tests/api/test_rbac_matrix.py",
                (("Неавторизованный запрос получает 401.", "An unauthenticated request returns 401."),
                 ("USER получает 403 без изменения данных.", "USER gets 403 without changing data."),
                 ("ADMIN выполняет разрешённую операцию.", "ADMIN performs the permitted action.")),
                ("api", "security"),
            ),
            _c(
                "cookie-session", "security", "basic",
                "Cookie-сессия", "Cookie session",
                "Проверьте установку, чтение и удаление cookie реальным HTTP-клиентом.",
                "Verify cookie set, read, and delete with a real HTTP client.",
                "/api/practice/cookies/*", "student_tests/api/test_cookies.py",
                (("Используется один Client с cookie jar.", "Use one Client with a cookie jar."),
                 ("Проверены HttpOnly и SameSite.", "Validate HttpOnly and SameSite."),
                 ("После удаления cookie не возвращается.", "The cookie is absent after deletion.")),
                ("api", "security"),
            ),
            _c(
                "input-boundaries", "security", "intermediate",
                "Границы входных данных", "Input boundaries",
                "Проверьте обязательные поля, типы, минимумы, максимумы и лишние поля.",
                "Verify required fields, types, minimums, maximums, and extra fields.",
                "POST /api/practice/resources", "student_tests/api/test_input_boundaries.py",
                (("Тесты построены из таблицы классов эквивалентности.", "Tests use an equivalence-class table."),
                 ("Проверено точное граничное значение и соседние значения.", "Validate exact boundaries and adjacent values."),
                 ("Ответ 422 проверяется по полям, а не целой строкой.", "Validate 422 by fields, not a whole message string.")),
                ("api", "security"),
            ),
            _c(
                "deterministic-rate-limit", "security", "intermediate",
                "Ограничение частоты запросов", "Deterministic rate limiting",
                "Проверьте разрешённый лимит, 429, Retry-After и сброс отдельного namespace.",
                "Verify the allowed quota, 429, Retry-After, and isolated namespace reset.",
                "GET /api/practice/rate-limit", "student_tests/api/test_rate_limit.py",
                (("Проверены RateLimit-Limit и RateLimit-Remaining.", "Validate RateLimit-Limit and RateLimit-Remaining."),
                 ("Первый запрос сверх лимита получает 429.", "The first over-limit request returns 429."),
                 ("Другой X-Test-Run-Id начинает с чистого лимита.", "A different X-Test-Run-Id starts with a fresh quota.")),
                ("api", "security"),
            ),
            _c(
                "cors-preflight", "security", "advanced",
                "CORS preflight-контракт", "CORS preflight contract",
                "Проверьте OPTIONS-запрос браузера, разрешённый Origin, метод и заголовки.",
                "Verify a browser OPTIONS request, allowed Origin, method, and headers.",
                "OPTIONS /api/practice/echo", "student_tests/contract/test_cors_preflight.py",
                (("Запрос содержит Origin и Access-Control-Request-Method.", "Send Origin and Access-Control-Request-Method."),
                 ("Проверены allow-origin, allow-methods и credentials.", "Validate allow-origin, allow-methods, and credentials."),
                 ("Фактический запрос проверен отдельно от preflight.", "Validate the actual request separately from preflight.")),
                ("api", "contract", "security"),
            ),
        ),
    ),
    Track(
        "ui",
        Text("UI и Playwright", "UI and Playwright"),
        Text("Надёжные локаторы, ожидания, формы, окна, iframe и Shadow DOM.", "Reliable locators, waits, forms, windows, iframes, and Shadow DOM."),
        (
            _c(
                "login-ui", "ui", "basic",
                "Вход через UI", "UI login",
                "Автоматизируйте позитивный вход, ошибку неверного пароля и прямой сброс пароля.",
                "Automate successful login, an invalid-password error, and direct password reset.",
                "/login and /forgot-password", "student_tests/ui/test_login.py",
                (("Используются role, label или data-testid локаторы.", "Use role, label, or data-testid locators."),
                 ("Нет sleep и зависимости от порядка тестов.", "No sleeps or test-order dependency."),
                 ("После reset старый пароль не работает, новый работает.", "After reset, the old password fails and the new one works.")),
                ("ui",),
            ),
            _c(
                "semantic-form", "ui", "basic",
                "Семантическая форма", "Semantic form",
                "Заполните форму разными типами контролов и проверьте результат.",
                "Fill a form with different control types and validate the result.",
                "/practice/components", "student_tests/ui/test_semantic_form.py",
                (("Локаторы ориентированы на поведение пользователя.", "Locators follow user-visible behavior."),
                 ("Форма проверена с Unicode и пустым обязательным полем.", "Test Unicode and an empty required field."),
                 ("Утверждения проверяют итоговое состояние.", "Assertions validate the resulting state.")),
                ("ui",),
            ),
            _c(
                "dynamic-content", "ui", "intermediate",
                "Динамический DOM без sleep", "Dynamic DOM without sleep",
                "Дождитесь появления и исчезновения элементов штатными ожиданиями Playwright.",
                "Wait for elements to appear and disappear using Playwright waits.",
                "/practice/components", "student_tests/ui/test_dynamic_content.py",
                (("В тесте отсутствует time.sleep.", "The test contains no time.sleep."),
                 ("Проверен промежуточный и конечный статус.", "Validate intermediate and final states."),
                 ("Тест устойчив к небольшой задержке среды CI.", "The test tolerates small CI delays.")),
                ("ui",),
            ),
            _c(
                "scoped-locators", "ui", "intermediate",
                "Строгие и scoped-локаторы", "Strict scoped locators",
                "Выберите нужные элементы среди повторяющихся подписей без nth как основного способа.",
                "Select elements among duplicate labels without relying on nth as the main strategy.",
                "/practice/components", "student_tests/ui/test_scoped_locators.py",
                (("Поиск ограничен контейнером карточки или строки.", "Search is scoped to a card or row."),
                 ("Strict mode не нарушается.", "Strict mode is not violated."),
                 ("Проверяется правильный объект, а не просто любой toast.", "Validate the correct object, not just any toast.")),
                ("ui",),
            ),
            _c(
                "browser-contexts", "ui", "advanced",
                "Iframe, Shadow DOM и новая вкладка", "Iframe, Shadow DOM, and new tab",
                "Напишите независимые проверки трёх изолированных контекстов страницы.",
                "Write independent checks for three isolated page contexts.",
                "/practice/components", "student_tests/ui/test_browser_contexts.py",
                (("Iframe проверяется через frame locator.", "Use a frame locator for the iframe."),
                 ("Shadow DOM доступен без XPath.", "Access Shadow DOM without XPath."),
                 ("Новая вкладка перехватывается до клика и закрывается.", "Capture the new tab before clicking and close it.")),
                ("ui",),
            ),
            _c(
                "responsive-ui", "ui", "advanced",
                "Адаптивность и визуальные состояния", "Responsive and visual states",
                "Проверьте ключевой сценарий на desktop и mobile viewport.",
                "Verify a key scenario on desktop and mobile viewports.",
                "/practice/components", "student_tests/ui/test_responsive.py",
                (("Размеры задаются параметрами теста.", "Viewport sizes are parametrized."),
                 ("Проверяется доступность действий, а не координаты.", "Validate action availability, not coordinates."),
                 ("Скриншот сохраняется только при сбое либо как осознанный baseline.", "Save screenshots on failure or as an intentional baseline.")),
                ("ui",),
            ),
            _c(
                "keyboard-accessibility", "ui", "intermediate",
                "Клавиатура и семантика доступности", "Keyboard and accessibility semantics",
                "Пройдите ключевую форму клавиатурой и проверьте имена, фокус и dialog.",
                "Complete the key form by keyboard and validate names, focus, and the dialog.",
                "/practice/components", "student_tests/ui/test_accessibility.py",
                (("Все поля имеют доступные имена и связаны с label.", "All controls have accessible names and associated labels."),
                 ("Tab-порядок позволяет выполнить сценарий без мыши.", "Tab order allows completing the scenario without a mouse."),
                 ("Dialog открывается, получает фокус и закрывается с Escape.", "The dialog opens, receives focus, and closes with Escape.")),
                ("ui",),
            ),
        ),
    ),
    Track(
        "integration",
        Text("Интеграции и данные", "Integrations and data"),
        Text("База данных, файлы, асинхронные операции, redirects и WebSocket.", "Database, files, asynchronous operations, redirects, and WebSocket."),
        (
            _c(
                "database-persistence", "integration", "intermediate",
                "API и состояние БД", "API and database state",
                "Создайте данные через API и подтвердите их сохранение прямым SQL-запросом.",
                "Create data through the API and confirm persistence with direct SQL.",
                "/api/auth/register + PostgreSQL", "student_tests/integration/test_database_state.py",
                (("DATABASE_URL берётся из окружения.", "Read DATABASE_URL from the environment."),
                 ("SQL параметризован, соединение закрывается.", "Use parametrized SQL and close the connection."),
                 ("Тест очищает только собственные данные.", "The test cleans up only its own data.")),
                ("integration",),
            ),
            _c(
                "async-job", "integration", "intermediate",
                "Polling асинхронной задачи", "Asynchronous job polling",
                "Запустите задачу и дождитесь терминального состояния с ограниченным deadline.",
                "Start a job and wait for a terminal state with a bounded deadline.",
                "/api/practice/jobs", "student_tests/integration/test_async_job.py",
                (("POST возвращает 202 и Location.", "POST returns 202 and Location."),
                 ("Polling имеет deadline и короткий интервал.", "Polling uses a deadline and short interval."),
                 ("Проверены COMPLETED и FAILED.", "Cover COMPLETED and FAILED.")),
                ("api", "integration"),
            ),
            _c(
                "file-roundtrip", "integration", "intermediate",
                "Загрузка и скачивание файла", "File upload and download",
                "Загрузите файл, проверьте метаданные и скачайте те же байты.",
                "Upload a file, validate metadata, and download the same bytes.",
                "/api/practice/files", "student_tests/integration/test_file_roundtrip.py",
                (("Проверены имя, размер, SHA-256 и Content-Disposition.", "Validate name, size, SHA-256, and Content-Disposition."),
                 ("Пустой и слишком большой файл отклоняются.", "Reject empty and oversized files."),
                 ("Временный файл создаётся через tmp_path.", "Create the temporary file via tmp_path.")),
                ("api", "integration"),
            ),
            _c(
                "redirect-chain", "integration", "basic",
                "Цепочка redirects", "Redirect chain",
                "Проверьте запрос с включённым и отключённым follow_redirects.",
                "Verify requests with follow_redirects enabled and disabled.",
                "GET /api/practice/redirect/{hops}", "student_tests/api/test_redirects.py",
                (("Проверены Location и история переходов.", "Validate Location and redirect history."),
                 ("Нулевая цепочка завершается 200.", "A zero-hop chain ends with 200."),
                 ("Слишком длинная цепочка отклоняется валидацией.", "An overly long chain is rejected by validation.")),
                ("api",),
            ),
            _c(
                "websocket-feed", "integration", "advanced",
                "События WebSocket", "WebSocket events",
                "Подключитесь к ленте, проверьте структуру события и корректное закрытие.",
                "Connect to the feed, validate event structure, and close cleanly.",
                "WS /ws/notifications", "student_tests/integration/test_websocket.py",
                (("Ожидание сообщения ограничено по времени.", "Message waiting is time-bounded."),
                 ("Проверяется JSON-контракт события.", "Validate the event JSON contract."),
                 ("Соединение закрывается даже при падении утверждения.", "Close the connection even when an assertion fails.")),
                ("integration",),
            ),
            _c(
                "webhook-recorder", "integration", "advanced",
                "Регистратор webhook", "Webhook recorder",
                "Отправьте несколько событий и проверьте их порядок, заголовки и очистку.",
                "Send events and verify ordering, headers, and cleanup.",
                "/api/practice/webhooks", "student_tests/integration/test_webhook_recorder.py",
                (("События изолированы X-Test-Run-Id.", "Events are isolated by X-Test-Run-Id."),
                 ("Проверены порядок и корреляционный заголовок.", "Validate ordering and a correlation header."),
                 ("Cleanup удаляет только namespace теста.", "Cleanup removes only the test namespace.")),
                ("api", "integration"),
            ),
        ),
    ),
    Track(
        "reliability",
        Text("Надёжность и CI", "Reliability and CI"),
        Text("Ретраи, таймауты, параллельность, отчёты и независимость тестов.", "Retries, timeouts, parallelism, reports, and test independence."),
        (
            _c(
                "retry-fail-first", "reliability", "advanced",
                "Контролируемый retry", "Controlled retry",
                "Обработайте fail-first только для безопасного идемпотентного запроса.",
                "Handle fail-first only for a safe idempotent request.",
                "X-Playground-Scenario: fail-first", "student_tests/api/test_retry_policy.py",
                (("Каждый тест использует уникальный X-Playground-Run.", "Each test uses a unique X-Playground-Run."),
                 ("Число попыток ограничено.", "The retry count is bounded."),
                 ("POST без идемпотентности автоматически не повторяется.", "A non-idempotent POST is not retried automatically.")),
                ("api", "reliability"),
            ),
            _c(
                "timeouts-and-malformed", "reliability", "intermediate",
                "Таймаут и повреждённый JSON", "Timeout and malformed JSON",
                "Проверьте тип исключения для медленного ответа и некорректного JSON.",
                "Validate exception types for a slow response and malformed JSON.",
                "X-Playground-Scenario: slow|malformed-json", "student_tests/api/test_failure_modes.py",
                (("Таймаут задан явно и тест завершается быстро.", "Set an explicit timeout and finish quickly."),
                 ("Проверяется конкретный класс исключения.", "Assert a specific exception class."),
                 ("Сбой содержит полезный диагностический контекст.", "The failure contains useful diagnostic context.")),
                ("api", "reliability"),
            ),
            _c(
                "parallel-isolation", "reliability", "advanced",
                "Изоляция параллельных тестов", "Parallel test isolation",
                "Докажите, что два запуска с разными namespace не влияют друг на друга.",
                "Prove that runs with different namespaces do not affect each other.",
                "/api/practice/resources", "student_tests/integration/test_parallel_isolation.py",
                (("Нет общих фиксированных email, имён и ключей.", "No shared fixed emails, names, or keys."),
                 ("Cleanup адресный и безопасный.", "Cleanup is targeted and safe."),
                 ("Тесты проходят в произвольном порядке.", "Tests pass in arbitrary order.")),
                ("integration", "reliability"),
            ),
            _c(
                "allure-diagnostics", "reliability", "intermediate",
                "Диагностика в Allure", "Allure diagnostics",
                "Добавьте шаги, параметры и безопасные вложения для ключевого end-to-end сценария.",
                "Add steps, parameters, and safe attachments for a key end-to-end scenario.",
                "Jenkins + Allure", "student_tests/ui/test_end_to_end.py",
                (("В отчёте понятны бизнес-шаг и место сбоя.", "The report shows the business step and failure point."),
                 ("Токены и пароли замаскированы.", "Tokens and passwords are masked."),
                 ("Trace, screenshot и video сохраняются при UI-сбое.", "Trace, screenshot, and video are retained on UI failure.")),
                ("ui", "reliability"),
            ),
            _c(
                "quality-gates", "reliability", "advanced",
                "Quality gates в Jenkins", "Jenkins quality gates",
                "Добавьте новый тест и убедитесь, что Jenkins автоматически его обнаруживает и публикует результат.",
                "Add a test and confirm Jenkins discovers and reports it automatically.",
                "student_tests/**/test_*.py", "student_tests/api/test_ci_discovery.py",
                (("Сбой теста делает соответствующую стадию красной.", "A test failure makes its stage red."),
                 ("Эталонные и пользовательские тесты видны раздельно.", "Reference and student tests are reported separately."),
                 ("Артефакты UI доступны после сбоя.", "UI artifacts remain available after failure.")),
                ("reliability",),
            ),
        ),
    ),
    Track(
        "business-flows",
        Text("Бизнес-процессы", "Business flows"),
        Text(
            "Реальные пользовательские и административные сценарии платформы.",
            "Real user and administration workflows of the platform.",
        ),
        (
            _c(
                "registration-ui", "business-flows", "basic",
                "Регистрация через UI", "UI registration",
                "Проверьте успешную регистрацию, обязательные поля и повторный email.",
                "Verify successful registration, required fields, and duplicate email.",
                "/register", "student_tests/ui/test_registration.py",
                (("Пользователь создаётся через уникальный email.", "Create a user with a unique email."),
                 ("Пароли и принятие условий проверяются сервером.", "Passwords and terms are validated server-side."),
                 ("Повторный email даёт понятную ошибку.", "Duplicate email produces a clear error.")),
                ("ui",),
            ),
            _c(
                "password-reset-ui", "business-flows", "intermediate",
                "Сброс пароля", "Password reset",
                "Докажите, что старый пароль перестаёт работать, а новый позволяет войти.",
                "Prove the old password stops working and the new password can log in.",
                "/forgot-password", "student_tests/ui/test_password_reset.py",
                (("Пользователь создаётся через user_factory.", "Create the user through user_factory."),
                 ("Проверены несовпадающие пароли.", "Cover mismatching passwords."),
                 ("Сценарий работает на RU и EN.", "The flow works in RU and EN.")),
                ("ui", "security"),
            ),
            _c(
                "profile-avatar", "business-flows", "intermediate",
                "Профиль и аватар", "Profile and avatar",
                "Проверьте сохранение профиля и безопасную загрузку изображения.",
                "Verify profile persistence and safe image upload.",
                "/profile", "student_tests/ui/test_profile_avatar.py",
                (("Поля сохраняются после перезагрузки.", "Fields survive reload."),
                 ("PNG/JPEG/WebP принимаются.", "PNG/JPEG/WebP are accepted."),
                 ("MIME spoofing и oversized-файл отклоняются.", "MIME spoofing and oversized files are rejected.")),
                ("ui", "security"),
            ),
            _c(
                "notifications-ui", "business-flows", "intermediate",
                "Уведомления и infinite scroll", "Notifications and infinite scroll",
                "Проверьте фильтры, подгрузку, отметку прочитанным и удаление.",
                "Verify filters, loading, mark-as-read, and deletion.",
                "/notifications", "student_tests/ui/test_notifications.py",
                (("Нет дубликатов при подгрузке.", "Loading does not create duplicates."),
                 ("Состояние подтверждается через API.", "Confirm state through the API."),
                 ("Чужое уведомление недоступно.", "Another user's notification is inaccessible.")),
                ("ui", "api"),
            ),
            _c(
                "admin-users", "business-flows", "advanced",
                "Администрирование пользователей", "User administration",
                "Проверьте изменение роли, блокировку, повторную активацию и audit log.",
                "Verify role changes, deactivation, reactivation, and audit log.",
                "/admin | /api/admin/*", "student_tests/ui/test_admin_users.py",
                (("Матрица USER/MANAGER/ADMIN параметризована.", "Parametrize USER/MANAGER/ADMIN."),
                 ("Администратор не блокирует себя.", "An administrator cannot disable self."),
                 ("Каждое действие появляется в audit log.", "Each action appears in the audit log.")),
                ("ui", "api", "security"),
            ),
            _c(
                "course-lifecycle", "business-flows", "advanced",
                "Жизненный цикл курса", "Course lifecycle",
                "Проверьте CRUD и правила DRAFT/PUBLISHED/ARCHIVED.",
                "Verify CRUD and DRAFT/PUBLISHED/ARCHIVED rules.",
                "/api/courses | /courses", "student_tests/api/test_course_lifecycle.py",
                (("Создание и изменение доступны нужным ролям.", "Create and update follow role rules."),
                 ("Каталог и enrollment учитывают статус.", "Catalog and enrollment respect lifecycle state."),
                 ("Удаление каскадно не оставляет сирот.", "Deletion leaves no orphan records.")),
                ("api", "integration", "security"),
            ),
            _c(
                "enrollment-race", "business-flows", "advanced",
                "Конкурентная запись на курс", "Concurrent enrollment",
                "Отправьте параллельные запросы и докажите уникальность enrollment.",
                "Send concurrent requests and prove enrollment uniqueness.",
                "POST /api/courses/{id}/enroll", "student_tests/integration/test_enrollment_race.py",
                (("Запросы стартуют конкурентно.", "Requests start concurrently."),
                 ("Ровно один запрос создаёт запись.", "Exactly one request creates a row."),
                 ("В БД существует единственная запись.", "Exactly one database row exists.")),
                ("integration", "reliability"),
            ),
            _c(
                "exam-scoring", "business-flows", "advanced",
                "Подсчёт результата экзамена", "Exam scoring",
                "Проверьте все типы вопросов, границу 60%, прогресс и сертификат.",
                "Verify all question types, the 60% boundary, progress, and certificate.",
                "/api/exams/*", "student_tests/api/test_exam_scoring.py",
                (("Проверены SINGLE, MULTI, TEXT и DND.", "Cover SINGLE, MULTI, TEXT, and DND."),
                 ("Проверены 59% и 60%.", "Cover 59% and 60%."),
                 ("Сертификат недоступен без успешной попытки.", "Certificate requires a passed attempt.")),
                ("api", "integration"),
            ),
            _c(
                "audit-consistency", "business-flows", "advanced",
                "Согласованность аудита", "Audit consistency",
                "Свяжите бизнес-действия, уведомления и audit log по данным БД.",
                "Relate business actions, notifications, and audit log using database state.",
                "/api/admin/audit + PostgreSQL", "student_tests/integration/test_audit_consistency.py",
                (("Проверены actor, action и payload.", "Validate actor, action, and payload."),
                 ("Неуспешная операция не создаёт ложный аудит.", "Failed operations do not create false audit."),
                 ("Данные очищаются через Test Data API.", "Data is cleaned through Test Data API.")),
                ("integration",),
            ),
            _c(
                "localization-flow", "business-flows", "intermediate",
                "Сквозная локализация RU/EN", "End-to-end RU/EN localization",
                "Проверьте смену языка на авторизации и защищённых страницах.",
                "Verify language switching on authentication and protected pages.",
                "POST /web/language", "student_tests/ui/test_localization.py",
                (("Язык меняется одним нажатием.", "Language changes in one click."),
                 ("Выбор сохраняется после login/logout.", "Selection survives login/logout."),
                 ("Динамические сообщения локализованы.", "Dynamic messages are localized.")),
                ("ui",),
            ),
        ),
    ),
    Track(
        "engineering-gates",
        Text("Инженерные quality gates", "Engineering quality gates"),
        Text(
            "Мутации, версии API, Redis, очередь, внешний mock, доступность и нагрузка.",
            "Mutations, API versions, Redis, queue, external mock, accessibility, and load.",
        ),
        (
            _c(
                "mutation-score", "engineering-gates", "advanced",
                "Mutation score", "Mutation score",
                "Добавьте мутации задачи в mutations.json и добейтесь их обнаружения.",
                "Add task mutations to mutations.json and make the tests kill them.",
                "GET /api/practice/mutations", "student_tests/mutations.json",
                (("Baseline остаётся зелёным.", "The baseline remains green."),
                 ("Каждая назначенная мутация убита.", "Every assigned mutation is killed."),
                 ("Mutation score соответствует порогу CI.", "Mutation score meets the CI threshold.")),
                ("reliability",),
            ),
            _c(
                "test-data-api", "engineering-gates", "intermediate",
                "Test Data API", "Test Data API",
                "Создавайте одноразовые данные фабриками и докажите адресную очистку.",
                "Create disposable data with factories and prove targeted cleanup.",
                "/api/test-support/*", "student_tests/integration/test_test_data_api.py",
                (("Данные двух run_id не пересекаются.", "Two run IDs remain isolated."),
                 ("Cleanup одного запуска не удаляет другой.", "One cleanup does not affect another run."),
                 ("API требует support key.", "The API requires a support key.")),
                ("integration", "security"),
            ),
            _c(
                "api-version-compatibility", "engineering-gates", "advanced",
                "Совместимость API v1/v2", "API v1/v2 compatibility",
                "Зафиксируйте legacy-контракт v1 и новый контракт v2.",
                "Lock the legacy v1 contract and the new v2 contract.",
                "/api/v1/courses | /api/v2/courses", "student_tests/contract/test_api_versions.py",
                (("v1 содержит Deprecation/Sunset/Link.", "v1 has Deprecation/Sunset/Link."),
                 ("Денежный контракт v2 точный.", "The v2 money contract is precise."),
                 ("OpenAPI описывает обе версии.", "OpenAPI documents both versions.")),
                ("contract",),
            ),
            _c(
                "redis-cache", "engineering-gates", "intermediate",
                "Redis cache", "Redis cache",
                "Проверьте roundtrip, TTL, namespace и cache miss.",
                "Verify roundtrip, TTL, namespace, and cache miss.",
                "/api/integrations/cache/*", "student_tests/integration/test_redis_cache.py",
                (("Сложный JSON сохраняется без потерь.", "Complex JSON roundtrips losslessly."),
                 ("TTL действительно истекает.", "TTL actually expires."),
                 ("Namespaces изолированы.", "Namespaces are isolated.")),
                ("integration",),
            ),
            _c(
                "rq-queue", "engineering-gates", "advanced",
                "Реальная RQ-очередь", "Real RQ queue",
                "Проверьте QUEUED/STARTED/FINISHED/FAILED и bounded polling.",
                "Verify QUEUED/STARTED/FINISHED/FAILED with bounded polling.",
                "/api/integrations/jobs", "student_tests/integration/test_rq_jobs.py",
                (("Задачу выполняет отдельный worker.", "A separate worker executes the job."),
                 ("Успех и ошибка имеют разные контракты.", "Success and failure have distinct contracts."),
                 ("Чужой run_id не читает job.", "Another run ID cannot read the job.")),
                ("integration", "reliability"),
            ),
            _c(
                "wiremock-external", "engineering-gates", "advanced",
                "Внешний сервис WireMock", "WireMock external service",
                "Проверьте success, not found, upstream error, timeout и запрос в mock.",
                "Verify success, not found, upstream error, timeout, and the mock request.",
                "/api/integrations/external/*", "student_tests/integration/test_external_service.py",
                (("HTTP-ошибки корректно отображаются наружу.", "HTTP failures are mapped correctly."),
                 ("Timeout ограничен.", "Timeout is bounded."),
                 ("WireMock verify подтверждает запрос.", "WireMock verify confirms the request.")),
                ("integration", "reliability"),
            ),
            _c(
                "axe-accessibility", "engineering-gates", "advanced",
                "Accessibility через axe-core", "Accessibility with axe-core",
                "Сканируйте ключевые состояния интерфейса и прикладывайте JSON нарушения.",
                "Scan key UI states and attach violation JSON.",
                "UI + axe-core", "student_tests/ui/test_accessibility.py",
                (("Проверены WCAG A/AA правила.", "Cover WCAG A/AA rules."),
                 ("Сканируются открытые диалоги и динамические состояния.", "Scan open dialogs and dynamic states."),
                 ("Ручные ограничения автоматизации отмечены в отчёте.", "Report manual-testing limitations.")),
                ("ui",),
            ),
            _c(
                "performance-p95", "engineering-gates", "advanced",
                "Нагрузочный p95 gate", "Performance p95 gate",
                "Запустите Locust headless и заблокируйте CI при нарушении p95/failure-rate.",
                "Run Locust headless and block CI on p95/failure-rate violations.",
                "performance/locustfile.py", "performance/locustfile.py",
                (("Профиль имеет ramp-up и конечную длительность.", "The profile has ramp-up and finite duration."),
                 ("Проверены minimum requests, p95 и failure ratio.", "Check minimum requests, p95, and failure ratio."),
                 ("CSV и HTML архивируются.", "CSV and HTML are archived.")),
                ("reliability",),
            ),
        ),
    ),
)

CHALLENGES = tuple(challenge for track in TRACKS for challenge in track.challenges)
CHALLENGES_BY_SLUG = {challenge.slug: challenge for challenge in CHALLENGES}


def serialize_challenge(challenge: Challenge, language: str) -> dict:
    """Возвращает контракт каталога без решения и учебного текста."""
    data = asdict(challenge)
    data["title"] = challenge.title.in_language(language)
    data["task"] = challenge.task.in_language(language)
    data["criteria"] = [item.in_language(language) for item in challenge.criteria]
    return data


def serialize_catalog(language: str) -> list[dict]:
    return [
        {
            "slug": track.slug,
            "title": track.title.in_language(language),
            "description": track.description.in_language(language),
            "challenges": [serialize_challenge(item, language) for item in track.challenges],
        }
        for track in TRACKS
    ]
